vich_uploader:
    db_driver: orm
    mappings:
        capsule_image:
            uri_prefix: /uploads/images/capsules
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true
